<?
	session_start();
	session_unset($_SESSION['id']);
	session_unset($_SESSION['nama']);
	session_unset($_SESSION['level']);
	session_unset($_SESSION['username']);
	session_unset($_SESSION['password']);
	session_destroy();
	header("Location:../");
?>